RDKCOM-2206 RDKBCMF-269 CcspLMLite device_gateway_association build failure
When the device_gateway_association DISTRO_FEATURES is observed,
the following build failure is observed:

CcspLMLite/source/lm/cosa_managementserver_dml.c: In function 'ManageableDevice_IsUpdated':
CcspLMLite/source/lm/cosa_managementserver_dml.c:179:41: error: variable 'pTmpSListEntry' set but not used [-Werror=unused-but-set-variable]
  179 |     PSINGLE_LINK_ENTRY                  pTmpSListEntry    = NULL;
      |                                         ^~~~~~~~~~~~~~
CcspLMLite/source/lm/cosa_managementserver_dml.c: In function 'findAndUpdateMatchedEntry':
CcspLMLite/source/lm/cosa_managementserver_dml.c:260:11: error: unused variable 'fp' [-Werror=unused-variable]
  260 |     FILE *fp =NULL;
      |           ^~
CcspLMLite/source/lm/cosa_managementserver_dml.c: In function 'CosaSListPushEntryByInsNum':
CcspLMLite/source/lm/cosa_managementserver_dml.c:310:37: error: unused variable 'returnStatus' [-Werror=unused-variable]
  310 |     ANSC_STATUS                     returnStatus      = ANSC_STATUS_SUCCESS;
      |                                     ^~~~~~~~~~~~
CcspLMLite/source/lm/cosa_managementserver_dml.c: In function 'ManageableDevice_Synchronize':
CcspLMLite/source/lm/cosa_managementserver_dml.c:370:42: error: unused variable 'retrycount' [-Werror=unused-variable]
  370 |     ULONG                                retrycount        = 0;
      |                                          ^~~~~~~~~~
CcspLMLite/source/lm/cosa_managementserver_dml.c:356:37: error: unused parameter 'hInsContext' [-Werror=unused-parameter]
  356 |         ANSC_HANDLE                 hInsContext
      |         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~
...
CcspLMLite/source/lm/cosa_managementserver_apis.c:43:11: error: unused variable 'fpLmlite' [-Werror=unused-variable]
   43 |     FILE *fpLmlite = NULL;
      |           ^~~~~~~~
cc1: all warnings being treated as errors

Reason for change: RDKBCMF-269 CcspLMLite device_gateway_association build failure
Test Procedure: None.
Risks: Low.

Signed-off-by: Simon Chung <simon_chung3@comcast.com>
(cherry picked from commit 1b328c10baf7f612b0a4d81a573c767d193cc620)
Change-Id: Iad2ba579aab48812a2a08ad39d6295b2b2525d51