RDKCOM-1971 RDKBCMF-256 CcspLMLite build errors
Build is failing when all warnings are treated as errors in meta-rdk-broadband/52103.
../../../../../../../../../rdkb/components/opensource/ccsp/CcspLMLite/source/lm/lm_main.c:2503:17: error: variable 'bridgemode' set but not used [-Werror=unused-but-set-variable]
     static BOOL bridgemode = FALSE;
                 ^~~~~~~~~~

Reason for change: RDKBCMF-256 CcspLMLite build errors
Test Procedure: None.
Risks: Low.
Signed-off-by: Stephen Barrett <stephen.barrett@accenture.com>

(cherry picked from commit d05c177c06a449ae7ff97e6e27ab7997c29a970f)
Change-Id: I3e4e61af0ef4647ffb1d04b83d327d0332e0d4d8