RDKCOM-376: fix libCcspLM and liblmapi linker order
libCcspLM requires symbols from liblmapi so should be listed after it
on the linker command line.
Fix for build issues such as:
 | i586-rdk-linux-musl-gcc -m32 -march=i586 -fno-omit-frame-pointer -fno-optimize-sibling-calls --sysroot=/.../build-qemux86broadband-musl/tmp/sysroots/qemux86broadband-musl -pipe -g -feliminate-unused-debug-types -fdebug-prefix-map=/.../build-qemux86broadband-musl/tmp/work/i586-rdk-linux-musl/ccsp-lm-lite/2.1+gitAUTOINC+9da8207ebe_be03aa7fc7-r0=/usr/src/debug/ccsp-lm-lite/2.1+gitAUTOINC+9da8207ebe_be03aa7fc7-r0 -fdebug-prefix-map=/.../build-qemux86broadband-musl/tmp/sysroots/x86_64-linux= -fdebug-prefix-map=/.../build-qemux86broadband-musl/tmp/sysroots/qemux86broadband-musl= -Os -pipe -DFEATURE_SUPPORT_RDKLOG -I/.../build-qemux86broadband-musl/tmp/sysroots/qemux86broadband-musl/usr/include/dbus-1.0 -I/.../build-qemux86broadband-musl/tmp/sysroots/qemux86broadband-musl/usr/include/libxml2 -I/.../build-qemux86broadband-musl/tmp/sysroots/qemux86broadband-musl/usr/lib/dbus-1.0/include -I/.../build-qemux86broadband-musl/tmp/sysroots/qemux86broadband-musl/usr/include/ccsp -I/.../build-qemux86broadband-musl/tmp/sysroots/qemux86broadband-musl/usr/include/mlt -I/.../build-qemux86broadband-musl/tmp/sysroots/qemux86broadband-musl/usr/include/trower-base64 -D_COSA_HAL_ -U_COSA_SIM_ -fno-exceptions -ffunction-sections -fdata-sections -fomit-frame-pointer -fno-strict-aliasing -D_ANSC_LINUX -D_ANSC_USER -D_ANSC_LITTLE_ENDIAN_ -D_CCSP_CWMP_TCP_CONNREQ_HANDLER -D_DSLH_STUN_ -D_NO_PKI_KB5_SUPPORT -D_BBHM_SSE_FILE_IO -D_ANSC_USE_OPENSSL_ -DENABLE_SA_KEY -D_ANSC_AES_USED_ -D_COSA_INTEL_USG_ATOM_ -D_COSA_FOR_COMCAST_ -D_NO_EXECINFO_H_ -DFEATURE_SUPPORT_SYSLOG -DBUILD_WEB -D_NO_ANSC_ZLIB_ -D_DEBUG -U_ANSC_IPV6_COMPATIBLE_ -D_ENABLE_BAND_STEERING_ -DUSE_NOTIFY_COMPONENT -D_BEACONRATE_SUPPORT -DDUAL_CORE_XB3 -DUTC_ENABLE_ATOM -D_ATM_SUPPORT -D_COSA_SIM_ -DPARODUS_ENABLE -I/.../build-qemux86broadband-musl/tmp/sysroots/qemux86broadband-musl/usr/include/libparodus -rdynamic -Wl,-O1 -Wl,--hash-style=gnu -Wl,--as-needed -o .libs/CcspLMLite CcspLMLite-ssp_messagebus_interface.o CcspLMLite-ssp_main.o CcspLMLite-ssp_action.o  -ldl -L=/usr/lib/..//lib ../../.libs/liblmapi.so ../../source-pc/lm/.libs/libCcspLM.a /.../build-qemux86broadband-musl/tmp/sysroots/qemux86broadband-musl/usr/lib/libccsp_common.so -lssl -lcrypto -L/var/tmp/pc-rdkb/lib /.../build-qemux86broadband-musl/tmp/sysroots/qemux86broadband-musl/usr/lib/libutapi.so /.../build-qemux86broadband-musl/tmp/sysroots/qemux86broadband-musl/usr/lib/libutctx.so /.../build-qemux86broadband-musl/tmp/sysroots/qemux86broadband-musl/usr/lib/libsysevent.so /.../build-qemux86broadband-musl/tmp/sysroots/qemux86broadband-musl/usr/lib/libsyscfg.so /.../build-qemux86broadband-musl/tmp/sysroots/qemux86broadband-musl/usr/lib/libulog.so /.../build-qemux86broadband-musl/tmp/sysroots/qemux86broadband-musl/usr/lib/libtirpc.so -lavro -lmsgpackc -ltrower-base64 /.../build-qemux86broadband-musl/tmp/sysroots/qemux86broadband-musl/usr/lib/libuuid.so -lnanomsg -lcimplog -lwrp-c -llibparodus -llibseshat /.../build-qemux86broadband-musl/tmp/sysroots/qemux86broadband-musl/usr/lib/librdkloggers.so /.../build-qemux86broadband-musl/tmp/sysroots/qemux86broadband-musl/usr/lib/liblog4c.so -lpthread /.../build-qemux86broadband-musl/tmp/sysroots/qemux86broadband-musl/usr/lib/libcurl.so /.../build-qemux86broadband-musl/tmp/sysroots/qemux86broadband-musl/usr/lib/libgnutls.so -largp -lnettle -lhogweed /.../build-qemux86broadband-musl/tmp/sysroots/qemux86broadband-musl/usr/lib/libgmp.so /.../build-qemux86broadband-musl/tmp/sysroots/qemux86broadband-musl/usr/lib/libxml2.so -lz /.../build-qemux86broadband-musl/tmp/sysroots/qemux86broadband-musl/usr/lib/libdbus-1.so /.../build-qemux86broadband-musl/tmp/sysroots/qemux86broadband-musl/usr/lib/libsystemd.so -lcap -lrt -lm -lresolv /.../build-qemux86broadband-musl/tmp/sysroots/qemux86broadband-musl/usr/lib/liblzma.so -pthread
 | ERROR: oe_runmake failed
 | ../../source-pc/lm/.libs/libCcspLM.a(libCcspLM_la-lm_main.o): In function `LM_get_host_info':
 | /usr/src/debug/ccsp-lm-lite/2.1+gitAUTOINC+9da8207ebe_be03aa7fc7-r0/git/source-pc/lm/lm_main.c:1817: undefined reference to `lm_get_all_hosts'
 | collect2: error: ld returned 1 exit status
 | make[3]: *** [CcspLMLite] Error 1
Signed-off-by: Andre McCurdy <armccurdy@gmail.com>

Reason for change: fix libCcspLM and liblmapi linker order
Test Procedure: None.
Risks: Low.

(cherry picked from commit a3d518c40194850d331f75f21c60bd15b8337438)

RDKCOM-377: fix gcc 7 build issues

 | /usr/src/debug/ccsp-lm-lite/2.1+gitAUTOINC+178c039544_9421836757-r0/git/source-pc/lm/lm_main.c:1392: error: undefined reference to '_mac_string_to_array'
 | collect2: error: ld returned 1 exit status
 | make[3]: *** [CcspLMLite] Error 1
Signed-off-by: Andre McCurdy <armccurdy@gmail.com>

Reason for change: fix gcc 7 build issues
Test Procedure: None.
Risks: Low.

Change-Id: I0faaf32ae1a70815e9dd60c720bfcf1ecff1931c
(cherry picked from commit 134d3087fc8da0eecafebd98655288261edb636b)
(cherry picked from commit b5f5443279ba1cebf0747a3a681eb54cf481929d)