RDKCOM-1929 RDKBCMF-252 CcspLMLite emulator build failure with libsyswrappe...
CcspLMLite emulator build failure with libsyswrapper change CcspLMLite/51860:
| ../../../../../../../../../rdkb/components/opensource/ccsp/CcspLMLite/source-pc/lm/lm_wrapper.c:674:6: error: call to 'format_error' declared with attribute error: command argument cannot be a variable
| ../../../../../../../../../rdkb/components/opensource/ccsp/CcspLMLite/source-pc/lm/lm_wrapper.c:676:6: error: call to 'format_error' declared with attribute error: command argument cannot be a variable

Reason for change: RDKBCMF-252 CcspLMLite emulator build failure with libsyswrappe...
Test Procedure: None.
Risks: Low.
Signed-off-by: Stephen Barrett <stephen.barrett@accenture.com>

(cherry picked from commit 426ec5b97fde90e5bca317756c9af032797af568)
Change-Id: Icdd1a8fccc33d66ce6a2cac88ca6b8245d66129c