RDKCOM-375: add missing libs to linker command line ( part 2 )
Add missing -lm to source builds + sync source and source-pc builds.
 | arm-rdk-linux-gnueabi-libtool: link: arm-rdk-linux-gnueabi-gcc -march=armv7ve -mthumb -mfpu=neon-vfpv4 -mfloat-abi=hard -mcpu=cortex-a7 -fno-omit-frame-pointer -fno-optimize-sibling-calls --sysroot=/.../rpi3-master-oe23/build-raspberrypi-rdk-broadband/tmp/work/cortexa7t2hf-neon-vfpv4-rdk-linux-gnueabi/ccsp-lm-lite/2.1+gitAUTOINC+9da8207ebe-r0/recipe-sysroot -pipe -g -feliminate-unused-debug-types -fdebug-prefix-map=/.../rpi3-master-oe23/build-raspberrypi-rdk-broadband/tmp/work/cortexa7t2hf-neon-vfpv4-rdk-linux-gnueabi/ccsp-lm-lite/2.1+gitAUTOINC+9da8207ebe-r0=/usr/src/debug/ccsp-lm-lite/2.1+gitAUTOINC+9da8207ebe-r0 -fdebug-prefix-map=/.../rpi3-master-oe23/build-raspberrypi-rdk-broadband/tmp/work/cortexa7t2hf-neon-vfpv4-rdk-linux-gnueabi/ccsp-lm-lite/2.1+gitAUTOINC+9da8207ebe-r0/recipe-sysroot-native= -fdebug-prefix-map=/.../rpi3-master-oe23/build-raspberrypi-rdk-broadband/tmp/work/cortexa7t2hf-neon-vfpv4-rdk-linux-gnueabi/ccsp-lm-lite/2.1+gitAUTOINC+9da8207ebe-r0/recipe-sysroot= -Os -pipe -DFEATURE_SUPPORT_RDKLOG -I/.../rpi3-master-oe23/build-raspberrypi-rdk-broadband/tmp/work/cortexa7t2hf-neon-vfpv4-rdk-linux-gnueabi/ccsp-lm-lite/2.1+gitAUTOINC+9da8207ebe-r0/recipe-sysroot/usr/include/dbus-1.0 -I/.../rpi3-master-oe23/build-raspberrypi-rdk-broadband/tmp/work/cortexa7t2hf-neon-vfpv4-rdk-linux-gnueabi/ccsp-lm-lite/2.1+gitAUTOINC+9da8207ebe-r0/recipe-sysroot/usr/include/libxml2 -I/.../rpi3-master-oe23/build-raspberrypi-rdk-broadband/tmp/work/cortexa7t2hf-neon-vfpv4-rdk-linux-gnueabi/ccsp-lm-lite/2.1+gitAUTOINC+9da8207ebe-r0/recipe-sysroot/usr/lib/dbus-1.0/include -I/.../rpi3-master-oe23/build-raspberrypi-rdk-broadband/tmp/work/cortexa7t2hf-neon-vfpv4-rdk-linux-gnueabi/ccsp-lm-lite/2.1+gitAUTOINC+9da8207ebe-r0/recipe-sysroot/usr/include/ccsp -I/.../rpi3-master-oe23/build-raspberrypi-rdk-broadband/tmp/work/cortexa7t2hf-neon-vfpv4-rdk-linux-gnueabi/ccsp-lm-lite/2.1+gitAUTOINC+9da8207ebe-r0/recipe-sysroot/usr/include/mlt -I/.../rpi3-master-oe23/build-raspberrypi-rdk-broadband/tmp/work/cortexa7t2hf-neon-vfpv4-rdk-linux-gnueabi/ccsp-lm-lite/2.1+gitAUTOINC+9da8207ebe-r0/recipe-sysroot/usr/include/trower-base64 -D_COSA_HAL_ -DPARODUS_ENABLE -I/.../rpi3-master-oe23/build-raspberrypi-rdk-broadband/tmp/work/cortexa7t2hf-neon-vfpv4-rdk-linux-gnueabi/ccsp-lm-lite/2.1+gitAUTOINC+9da8207ebe-r0/recipe-sysroot/usr/include/libparodus -U_COSA_SIM_ -fno-exceptions -ffunction-sections -fdata-sections -fomit-frame-pointer -fno-strict-aliasing -D_ANSC_LINUX -D_ANSC_USER -D_ANSC_LITTLE_ENDIAN_ -D_CCSP_CWMP_TCP_CONNREQ_HANDLER -D_DSLH_STUN_ -D_NO_PKI_KB5_SUPPORT -D_BBHM_SSE_FILE_IO -D_ANSC_USE_OPENSSL_ -DENABLE_SA_KEY -D_ANSC_AES_USED_ -D_COSA_INTEL_USG_ARM_ -D_COSA_FOR_COMCAST_ -D_NO_EXECINFO_H_ -DFEATURE_SUPPORT_SYSLOG -DBUILD_WEB -D_NO_ANSC_ZLIB_ -D_DEBUG -U_ANSC_IPV6_COMPATIBLE_ -D_COSA_BCM_ARM_ -DUSE_NOTIFY_COMPONENT -D_PLATFORM_RASPBERRYPI_ -D_COSA_INTEL_USG_ATOM_ -DENABLE_SD_NOTIFY -DCOSA_DML_WIFI_FEATURE_LoadPsmDefaults -UPARODUS_ENABLE -rdynamic -Wl,-O1 -Wl,--hash-style=gnu -Wl,--as-needed -o .libs/CcspLMLite CcspLMLite-ssp_messagebus_interface.o CcspLMLite-ssp_main.o CcspLMLite-ssp_action.o  -ldl ../../.libs/liblmapi.so ../../source/lm/.libs/libCcspLM.a -lccsp_common -lsysevent -lutapi -lutctx -lulog -lavro -lmsgpackc -ltrower-base64 -luuid -lnanomsg -lcimplog -lwrp-c -llibparodus -lrdkloggers -lcurl -lxml2
 | ERROR: oe_runmake failed
 | /usr/src/debug/ccsp-lm-lite/2.1+gitAUTOINC+9da8207ebe-r0/git/source/Ssp/ssp_messagebus_interface.c:39: error: undefined reference to 'dbus_message_get_interface'
 | /usr/src/debug/ccsp-lm-lite/2.1+gitAUTOINC+9da8207ebe-r0/git/source/Ssp/ssp_messagebus_interface.c:40: error: undefined reference to 'dbus_message_get_member'
 | /usr/src/debug/ccsp-lm-lite/2.1+gitAUTOINC+9da8207ebe-r0/git/source/Ssp/ssp_messagebus_interface.c:43: error: undefined reference to 'dbus_message_new_method_return'
 | /usr/src/debug/ccsp-lm-lite/2.1+gitAUTOINC+9da8207ebe-r0/git/source/lm/lm_main.c:699: error: undefined reference to 'syscfg_set'
 | /usr/src/debug/ccsp-lm-lite/2.1+gitAUTOINC+9da8207ebe-r0/git/source/lm/lm_main.c:705: error: undefined reference to 'syscfg_commit'
 | /usr/src/debug/ccsp-lm-lite/2.1+gitAUTOINC+9da8207ebe-r0/git/source/lm/lm_main.c:2621: error: undefined reference to 'mq_open'
 | /usr/src/debug/ccsp-lm-lite/2.1+gitAUTOINC+9da8207ebe-r0/git/source/lm/lm_main.c:2631: error: undefined reference to 'mq_send'
 | /usr/src/debug/ccsp-lm-lite/2.1+gitAUTOINC+9da8207ebe-r0/git/source/lm/lm_main.c:2632: error: undefined reference to 'mq_close'
 | /usr/src/debug/ccsp-lm-lite/2.1+gitAUTOINC+9da8207ebe-r0/git/source/lm/lm_main.c:2174: error: undefined reference to 'syscfg_init'
 | /usr/src/debug/ccsp-lm-lite/2.1+gitAUTOINC+9da8207ebe-r0/git/source/lm/lm_main.c:2175: error: undefined reference to 'syscfg_get'
 | /usr/src/debug/ccsp-lm-lite/2.1+gitAUTOINC+9da8207ebe-r0/git/source/lm/lm_main.c:2183: error: undefined reference to 'syscfg_get'
 | /usr/src/debug/ccsp-lm-lite/2.1+gitAUTOINC+9da8207ebe-r0/git/source/lm/lm_main.c:2217: error: undefined reference to 'pthread_create'
 | /usr/src/debug/ccsp-lm-lite/2.1+gitAUTOINC+9da8207ebe-r0/git/source/lm/lm_main.c:2227: error: undefined reference to 'pthread_create'
 | /usr/src/debug/ccsp-lm-lite/2.1+gitAUTOINC+9da8207ebe-r0/git/source/lm/lm_main.c:2232: error: undefined reference to 'pthread_create'
 | /usr/src/debug/ccsp-lm-lite/2.1+gitAUTOINC+9da8207ebe-r0/git/source/lm/lm_main.c:2238: error: undefined reference to 'pthread_create'
 | /usr/src/debug/ccsp-lm-lite/2.1+gitAUTOINC+9da8207ebe-r0/git/source/lm/lm_main.c:2196: error: undefined reference to 'syscfg_set'
 | /usr/src/debug/ccsp-lm-lite/2.1+gitAUTOINC+9da8207ebe-r0/git/source/lm/lm_main.c:2200: error: undefined reference to 'syscfg_commit'
 | /usr/src/debug/ccsp-lm-lite/2.1+gitAUTOINC+9da8207ebe-r0/git/source/lm/lm_main.c:2713: error: undefined reference to 'mq_open'
 | /usr/src/debug/ccsp-lm-lite/2.1+gitAUTOINC+9da8207ebe-r0/git/source/lm/lm_main.c:2727: error: undefined reference to 'mq_send'
 | /usr/src/debug/ccsp-lm-lite/2.1+gitAUTOINC+9da8207ebe-r0/git/source/lm/lm_main.c:2728: error: undefined reference to 'mq_close'
 | /usr/src/debug/ccsp-lm-lite/2.1+gitAUTOINC+9da8207ebe-r0/git/source/lm/lm_main.c:572: error: undefined reference to 'syscfg_set'
 | /usr/src/debug/ccsp-lm-lite/2.1+gitAUTOINC+9da8207ebe-r0/git/source/lm/lm_main.c:578: error: undefined reference to 'syscfg_commit'
 | /usr/src/debug/ccsp-lm-lite/2.1+gitAUTOINC+9da8207ebe-r0/git/source/lm/lm_main.c:1746: error: undefined reference to 'mq_open'
 | /usr/src/debug/ccsp-lm-lite/2.1+gitAUTOINC+9da8207ebe-r0/git/source/lm/lm_main.c:1756: error: undefined reference to 'mq_receive'
 | /usr/src/debug/ccsp-lm-lite/2.1+gitAUTOINC+9da8207ebe-r0/git/source/lm/lm_main.c:2504: error: undefined reference to 'mq_open'
 | /usr/src/debug/ccsp-lm-lite/2.1+gitAUTOINC+9da8207ebe-r0/git/source/lm/lm_main.c:2514: error: undefined reference to 'mq_send'
 | /usr/src/debug/ccsp-lm-lite/2.1+gitAUTOINC+9da8207ebe-r0/git/source/lm/lm_main.c:2515: error: undefined reference to 'mq_close'
 | /usr/src/debug/ccsp-lm-lite/2.1+gitAUTOINC+9da8207ebe-r0/git/source/lm/lm_wrapper.c:1437: error: undefined reference to 'syscfg_get'
 | /usr/src/debug/ccsp-lm-lite/2.1+gitAUTOINC+9da8207ebe-r0/git/source/lm/lm_wrapper.c:1439: error: undefined reference to 'syscfg_get'
 | /usr/src/debug/ccsp-lm-lite/2.1+gitAUTOINC+9da8207ebe-r0/git/source/lm/lm_wrapper.c:1502: error: undefined reference to 'syscfg_set'
 | /usr/src/debug/ccsp-lm-lite/2.1+gitAUTOINC+9da8207ebe-r0/git/source/lm/lm_wrapper.c:1508: error: undefined reference to 'syscfg_commit'
 | collect2: error: ld returned 1 exit status
 | make[3]: *** [CcspLMLite] Error 1
Signed-off-by: Andre McCurdy <armccurdy@gmail.com>

Reason for change: add missing libs to linker command line ( part 2 )
Test Procedure: None.
Risks: Low.

(cherry picked from commit d4e3db28e2f48f15f31406076d96697342633388)
(cherry picked from commit 1143bd5dab819a53c81de09045b140401a44bde1)

Change-Id: I335991fb121c59cb669a9405479e6bd741081666