RDKCOM-4072: REFPLTB-2543 : Latest rpi4 64bit build is breaking in ccsp-lm-l...
Reason for change : Observed below errors,
../../../../../../../../../rdkb/components/opensource/ccsp/CcspLMLite/source/lm/webpa_interface.c: In function 'get_ActiveInterface':
../../../../../../../../../rdkb/components/opensource/ccsp/CcspLMLite/source/lm/webpa_interface.c:548:40: error: '%s' directive output may be truncated writing up to 159 bytes into a region of size 100 [-Werror=format-truncation=]
  548 |      snprintf(buffer, sizeof(buffer), "%s,", interfaceUp[i]); // appending all active interface with comma
      |                                        ^~
../../../../../../../../../rdkb/components/opensource/ccsp/CcspLMLite/source/lm/webpa_interface.c:548:6: note: 'snprintf' output between 2 and 161 bytes into a destination of size 100
  548 |      snprintf(buffer, sizeof(buffer), "%s,", interfaceUp[i]); // appending all active interface with comma
      |      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../../../../../../../../../rdkb/components/opensource/ccsp/CcspLMLite/source/lm/webpa_interface.c: At top level:
cc1: error: unrecognized command line option '-Wno-array-parameter' [-Werror]
cc1: error: unrecognized command line option '-Wno-enum-conversion' [-Werror]
cc1: all warnings being treated as errors
Test Procedure: bitbake ccsp-lm-lite should be successful in 64bit compilation
Risks: Low
Signed-off-by: keerthana.p <keerthana_pandurangan@comcast.com>

Reason for change: REFPLTB-2543 : Latest rpi4 64bit build is breaking in ccsp-lm-l...

(cherry picked from commit 5026c88306cba7fd431bd19d9b060be7c53a3ff7)
Change-Id: Ibef04d3e830a9b368831510e6e6b33bc9f399e30